# Generated by Django 3.2.1 on 2021-05-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['id'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterField(
            model_name='course',
            name='course_title',
            field=models.CharField(max_length=255, verbose_name='Course title'),
        ),
        migrations.AlterField(
            model_name='course',
            name='finish_date',
            field=models.DateField(verbose_name='Course finish date'),
        ),
        migrations.AlterField(
            model_name='course',
            name='lectures_count',
            field=models.PositiveIntegerField(verbose_name='Count of lectures'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(verbose_name='Course start date'),
        ),
    ]
